namespace: fsas
name: primergy
version: 3.0.1
readme: README.md
description: Ansible iRMC Collection for PRIMERGY Distribution by Fsas Technologies Inc..
repository: https://github.com/fujitsu/ansible-irmc-integration

authors:
  - Shinya Hamano <hamano.shinya@fujitsu.com>
  - Yutaka Kamioka <yutaka.kamioka@fujitsu.com>
  - Tomohisa Nakai <nakai.tomohisa@fujitsu.com>

license:
  - GPL-3.0-or-later

tags:
  - fsas
  - fsastech
  - fsas_technologies
  - primergy
  - irmc
  - redfish
  - infrastructure
  - windows
  - tools

build_ignore:
  - examples
  - group_vars
  - host_vars
  - tests
  - inventory.ini
  - ansible.cfg
  - pyproject.toml
  - requirements*
  - uv.lock
  - .*
